"use client";
import { useState } from "react";

const offers=[["🏨","Hotels & Resorts","Up to 10% GBK","Stay and earn"],["✈️","Tours & Travel","Up to 10% GBK","Travel and earn"],["🍽️","Restaurants & Cafés","Up to 5% GBK","Dine and earn"],["🛍️","Stores & Supermarkets","2–10% GBK","Shop and earn"],["🏠","Real Estate","GBK offers","Property services and leads"],["🔧","Local Services","Up to 20% GBK","Use and earn"]];
const languages=["English","हिन्दी","తెలుగు","বাংলা","தமிழ்","मराठी","Español","العربية","Français","Português"];
const countries=["Global","India","United Arab Emirates","United States","United Kingdom","Singapore","Australia","Canada","Saudi Arabia","Malaysia"];
const roles=[
 {icon:"👤",title:"Customer",text:"Find participating businesses, pay normally in local currency and receive GBK rewards.",items:["Earn GBK","Hold • Swap • Transfer"]},
 {icon:"🏪",title:"Merchant",text:"Register your business, choose a loyalty offer, approve/fund GBK and receive eligible leads.",items:["5%–20% loyalty","Automatic reward distribution"]},
 {icon:"🌍",title:"Founder",text:"Country or Global Founder. Add businesses and earn the Founder share from verified loyalty sales.",items:["Add businesses","Track earnings • Swap • Transfer"]}
];

export default function Home(){
 const [query,setQuery]=useState(""); const [language,setLanguage]=useState("English"); const [country,setCountry]=useState("Global"); const [role,setRole]=useState<string|null>(null);
 const [installPrompt,setInstallPrompt]=useState<any>(null); const [installed,setInstalled]=useState(false);
 useState(()=>{ if(typeof window!=="undefined"){const w=window as any; const h=(e:any)=>{e.preventDefault();setInstallPrompt(e)}; w.addEventListener("beforeinstallprompt",h); setInstalled(w.matchMedia("(display-mode: standalone)").matches); if("serviceWorker" in navigator) navigator.serviceWorker.register("/sw.js").catch(()=>{}); return()=>w.removeEventListener("beforeinstallprompt",h)}});
 const install=async()=>{if(installPrompt){await installPrompt.prompt();setInstallPrompt(null)}else alert("On iPhone/iPad: Share → Add to Home Screen. On Android: browser menu → Install app.");};
 const scroll=()=>document.getElementById("roles")?.scrollIntoView({behavior:"smooth"});
 return <main className="shell">
  <header className="topbar"><div className="brand"><span className="brandMark">G</span><div><strong>GBK AI</strong><small>LOYALTY</small></div></div><div className="topActions"><select value={language} onChange={e=>setLanguage(e.target.value)} aria-label="Language">{languages.map(x=><option key={x}>{x}</option>)}</select><select value={country} onChange={e=>setCountry(e.target.value)} aria-label="Country">{countries.map(x=><option key={x}>{x}</option>)}</select><button className="walletBtn" onClick={()=>setRole("Customer")}>Connect Wallet</button></div></header>
  <div className="globalBar"><span>🌐 {country}</span><span>🗣️ {language}</span>{!installed&&<button className="installBtn" onClick={install}>{installPrompt?"📲 Install App":"📲 PWA App"}</button>}</div>
  <section className="hero"><div className="eyebrow">🌐 GLOBAL LOYALTY</div><h1>Shop • Earn • Hold • Swap • Transfer</h1><p>One simple loyalty system for customers, merchants and Country / Global Founder Members.</p>
   <div className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="What are you looking for?"/><button onClick={scroll}>Search</button></div>
   <div className="suggestions"><button onClick={()=>setQuery("restaurants with GBK rewards")}>🍽️ Restaurants</button><button onClick={()=>setQuery("hotels with GBK offers")}>🏨 Hotels</button><button onClick={()=>setQuery("tours and travel")}>✈️ Travel</button><button onClick={()=>setQuery("local services")}>🔧 Services</button></div>
  </section>
  <section id="roles" className="roleSection"><div className="sectionHead"><div><span className="eyebrow">ONE APP • THREE ROLES</span><h2>Choose how you use GBK Loyalty</h2></div></div><div className="roleGrid">{roles.map(r=><button className="roleCard" key={r.title} onClick={()=>setRole(r.title)}><div className="roleIcon">{r.icon}</div><h3>{r.title}</h3><p>{r.text}</p><div>{r.items.map(i=><span className="roleTag" key={i}>{i}</span>)}</div><b>Get started →</b></button>)}</div></section>
  <section className="split"><div className="panel"><span className="eyebrow">MERCHANT OFFER</span><h2>Simple reward distribution</h2><p>Merchant chooses the total loyalty offer. The system automatically splits it after payment verification.</p><div className="formula"><span>Customer</span><strong>60%</strong><span>Founder</span><strong>20%</strong><span>Platform</span><strong>20%</strong></div><small>Example: 10% merchant offer → 6% customer + 2% Founder + 2% platform.</small></div><div className="panel"><span className="eyebrow">AUTOMATIC CONTROL</span><h2>Approved + funded = active</h2><p>Payment verified → merchant identified → approval and balance checked → reward distributed → blockchain record.</p><div className="status">🟢 Active merchant <span>Eligible for leads</span></div><div className="status paused">⏸ Below 50% balance <span>Pause new reward leads</span></div></div></section>
  <section className="stats"><div><b>0 GBK</b><span>Rewards earned</span></div><div><b>0</b><span>Reward transactions</span></div><button onClick={()=>setRole("Customer")}>👛 Connect wallet</button></section>
  <section id="offers"><div className="sectionHead"><div><span className="eyebrow">🎁 DISCOVER</span><h2>GBK Rewards Near You</h2></div><button className="textBtn">View all</button></div><div className="grid">{offers.map(([icon,title,reward,note])=><article className="card" key={title}><div className="icon">{icon}</div><h3>{title}</h3><strong>{reward}</strong><p>{note} with participating businesses.</p><span className="arrow">›</span></article>)}</div></section>
  <section className="how"><span className="eyebrow">HOW IT WORKS</span><h2>Simple, automatic and traceable.</h2><div className="steps"><div><b>01</b><h3>Pay</h3><p>Customer pays the merchant normally in local currency.</p></div><div><b>02</b><h3>Verify</h3><p>Payment and order are verified before any reward is released.</p></div><div><b>03</b><h3>Distribute</h3><p>Merchant GBK automatically goes to Customer + Founder + Platform.</p></div></div></section>
  <section className="merchant"><div><span className="eyebrow">FOR BUSINESSES</span><h2>Activate loyalty. Receive eligible leads.</h2><p>Register, connect your wallet, choose 5%–20%, approve and fund your GBK reward balance.</p></div><button onClick={()=>setRole("Merchant")}>Register as Merchant →</button></section>
  {role&&<div className="modalBackdrop" onClick={()=>setRole(null)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setRole(null)}>×</button><div className="roleIcon">{roles.find(r=>r.title===role)?.icon}</div><h2>{role} registration</h2><p>Start with simple registration. Wallet connection, verification and role-specific setup come next.</p><input placeholder="Full name / Business name"/><input placeholder="Mobile or email"/><button className="primary">Continue →</button><small>No reward or token transfer happens from this screen.</small></div></div>}
  <nav className="bottomNav"><a className="active">⌂<span>Home</span></a><a onClick={()=>setRole("Customer")}>⌕<span>Explore</span></a><a onClick={()=>setRole("Customer")}>🎁<span>Rewards</span></a><a onClick={()=>setRole("Customer")}>👛<span>Wallet</span></a><a onClick={()=>setRole("Customer")}>☻<span>Profile</span></a></nav>
 </main>;
}